### ISSUE TITLE
Bottom cards overlapping

### ISSUE THREAD

**Issue by 0PandaDEV** [ciderapp/cider.sh-remake#2]
At the bottom of the page, the cards there representing the reviews are overlapping. I don't know if this is intentional.

![image](https://github.com/ciderapp/cider.sh-remake/assets/70103896/524aa2a2-533f-4d06-8fe2-cf5ffb577502)
![image](https://github.com/ciderapp/cider.sh-remake/assets/70103896/6a007c0c-6bea-4325-a56e-f8461c015b23)

**Comment by yazninja** [comment]
its a slider, it automatically moves, this is intentional and I don't see how its overlapping
